const defaults={profile:{weight:61.2,height:165,age:46,activity:1.55,deficit:20},macros:{A:[30,40,30],B:[30,45,25],C:[35,20,45]},week:{Lundi:'A',Mardi:'B',Mercredi:'A',Jeudi:'B',Vendredi:'A',Samedi:'C',Dimanche:'C'},weekOverrides:{},consumed:{},measures:[],customRecipes:[]};
let state=JSON.parse(localStorage.getItem('nutritionPWA')||'null')||structuredClone(defaults);const save=()=>localStorage.setItem('nutritionPWA',JSON.stringify(state));
const activities=[['Sédentaire',1.2],['Légèrement actif',1.375],['Légèrement actif + marche',1.45],['Modérément actif',1.55],['Très actif',1.725],['Super actif',1.9]];
const recipes=[
{name:'Œufs, pain complet & avocat',cat:'Petit-déjeuner',kcal:420,p:24,c:34,f:21,ingredients:'2 œufs · 70 g pain complet · 60 g avocat · tomates'},
{name:'Skyr, fruits rouges & amandes',cat:'Petit-déjeuner',kcal:330,p:28,c:31,f:10,ingredients:'250 g skyr · 120 g fruits rouges · 18 g amandes · 8 g miel'},
{name:'Tartines ricotta & saumon',cat:'Petit-déjeuner',kcal:390,p:27,c:37,f:15,ingredients:'80 g pain complet · 70 g ricotta · 70 g saumon fumé · concombre'},
{name:'Poulet, riz & courgettes',cat:'Déjeuner',kcal:520,p:48,c:58,f:11,ingredients:'150 g poulet · 70 g riz cru · 200 g courgettes · 8 g huile d’olive'},
{name:'Saumon, pommes de terre & brocoli',cat:'Déjeuner',kcal:560,p:39,c:48,f:23,ingredients:'150 g saumon · 260 g pommes de terre · 200 g brocoli'},
{name:'Bowl dinde & quinoa',cat:'Déjeuner',kcal:510,p:45,c:51,f:14,ingredients:'150 g dinde · 65 g quinoa cru · 200 g légumes · 8 g huile d’olive'},
{name:'Boule énergie cacao-amande',cat:'Collation',kcal:95,p:3,c:11,f:5,ingredients:'1 boule ~25 g · dattes · amandes · cacao pur'},
{name:'Boule énergie coco-cacahuète',cat:'Collation',kcal:105,p:4,c:9,f:7,ingredients:'1 boule ~25 g · dattes · cacahuètes · coco'},
{name:'Yaourt grec, kiwi & noix',cat:'Collation',kcal:245,p:18,c:22,f:10,ingredients:'180 g yaourt grec · 1 kiwi · 15 g noix'},
{name:'Cabillaud, patate douce & haricots verts',cat:'Dîner',kcal:445,p:43,c:47,f:9,ingredients:'170 g cabillaud · 220 g patate douce · 200 g haricots verts · 7 g huile'},
{name:'Omelette légumes & feta',cat:'Dîner',kcal:430,p:31,c:18,f:26,ingredients:'3 œufs · 250 g légumes · 45 g feta · 5 g huile d’olive'},
{name:'Crevettes, riz & légumes',cat:'Dîner',kcal:475,p:39,c:55,f:10,ingredients:'180 g crevettes · 65 g riz cru · 250 g légumes · 6 g huile'}];
const mealSplit={'Petit-déjeuner':.25,'Déjeuner':.32,'Collation':.13,'Dîner':.30};
const mealOrder=['Petit-déjeuner','Déjeuner','Collation','Dîner'];
const adjustableRecipes={
'Œufs, pain complet & avocat':[{n:'Œufs',g:100,min:50,max:150,k:143,p:12.6,c:.7,f:9.5},{n:'Pain complet',g:70,min:35,max:120,k:247,p:13,c:41,f:4.2},{n:'Avocat',g:60,min:25,max:100,k:160,p:2,c:8.5,f:14.7},{n:'Tomates',g:120,min:80,max:250,k:18,p:.9,c:3.9,f:.2}],
'Skyr, fruits rouges & amandes':[{n:'Skyr',g:250,min:150,max:350,k:63,p:11,c:4,f:.2},{n:'Fruits rouges',g:120,min:80,max:220,k:45,p:1,c:8,f:.5},{n:'Amandes',g:18,min:8,max:30,k:579,p:21.2,c:21.6,f:49.9},{n:'Miel',g:8,min:0,max:18,k:304,p:0,c:82.4,f:0}],
'Poulet, riz & courgettes':[{n:'Poulet',g:150,min:100,max:220,k:165,p:31,c:0,f:3.6},{n:'Riz cru',g:70,min:35,max:110,k:360,p:7,c:79,f:.7},{n:'Courgettes',g:200,min:150,max:350,k:17,p:1.2,c:3.1,f:.3},{n:'Huile d’olive',g:8,min:3,max:15,k:884,p:0,c:0,f:100}],
'Saumon, pommes de terre & brocoli':[{n:'Saumon',g:150,min:100,max:200,k:208,p:20,c:0,f:13},{n:'Pommes de terre',g:260,min:150,max:380,k:77,p:2,c:17,f:.1},{n:'Brocoli',g:200,min:150,max:350,k:34,p:2.8,c:6.6,f:.4}],
'Bowl dinde & quinoa':[{n:'Dinde',g:150,min:100,max:220,k:135,p:29,c:0,f:1.6},{n:'Quinoa cru',g:65,min:35,max:100,k:368,p:14,c:64,f:6},{n:'Légumes',g:200,min:150,max:350,k:30,p:1.5,c:5,f:.3},{n:'Huile d’olive',g:8,min:3,max:15,k:884,p:0,c:0,f:100}],
'Yaourt grec, kiwi & noix':[{n:'Yaourt grec',g:180,min:120,max:300,k:73,p:9.5,c:3.9,f:2},{n:'Kiwi',g:100,min:70,max:180,k:61,p:1.1,c:14.7,f:.5},{n:'Noix',g:15,min:5,max:25,k:654,p:15,c:14,f:65}],
'Cabillaud, patate douce & haricots verts':[{n:'Cabillaud',g:170,min:120,max:240,k:82,p:18,c:0,f:.7},{n:'Patate douce',g:220,min:130,max:340,k:86,p:1.6,c:20,f:.1},{n:'Haricots verts',g:200,min:150,max:350,k:31,p:1.8,c:7,f:.2},{n:'Huile d’olive',g:7,min:3,max:14,k:884,p:0,c:0,f:100}],
'Omelette légumes & feta':[{n:'Œufs',g:150,min:100,max:200,k:143,p:12.6,c:.7,f:9.5},{n:'Légumes',g:250,min:180,max:400,k:30,p:1.5,c:5,f:.3},{n:'Feta',g:45,min:20,max:70,k:265,p:14,c:4,f:21},{n:'Huile d’olive',g:5,min:2,max:10,k:884,p:0,c:0,f:100}],
'Crevettes, riz & légumes':[{n:'Crevettes',g:180,min:120,max:250,k:99,p:24,c:.2,f:.3},{n:'Riz cru',g:65,min:35,max:105,k:360,p:7,c:79,f:.7},{n:'Légumes',g:250,min:180,max:400,k:30,p:1.5,c:5,f:.3},{n:'Huile d’olive',g:6,min:2,max:12,k:884,p:0,c:0,f:100}]
};
function nutrient(i,g){let q=g/100;return{kcal:i.k*q,p:i.p*q,c:i.c*q,f:i.f*q}}
function sumIngredients(items,grams){return items.reduce((a,i,j)=>{let n=nutrient(i,grams[j]);for(let k of ['kcal','p','c','f'])a[k]+=n[k];return a},{kcal:0,p:0,c:0,f:0})}
function recipeItems(r){return r.customItems?.length?r.customItems:adjustableRecipes[r.name]}
function fitRecipe(r,goal){let items=recipeItems(r);if(!items)return null;let grams=items.map(i=>i.g), keys=['kcal','p','c','f'];let scales={kcal:Math.max(150,goal.kcal),p:Math.max(15,goal.p),c:Math.max(20,goal.c),f:Math.max(8,goal.f)};function score(gs){let x=sumIngredients(items,gs);return keys.reduce((z,k)=>z+Math.pow((x[k]-goal[k])/scales[k],2),0)}let best=score(grams);for(let pass=0;pass<12;pass++){for(let j=0;j<items.length;j++){let cur=grams[j],candidate=cur;for(let g=items[j].min;g<=items[j].max;g+=5){let test=[...grams];test[j]=g;let sc=score(test);if(sc<best){best=sc;candidate=g}}grams[j]=candidate}}return{items:items.map((i,j)=>({...i,g:grams[j]})),...sumIngredients(items,grams),score:best}}
function remaining(){let t=target(typeToday()),u=totals();return{kcal:Math.max(0,t.kcal-u.kcal),p:Math.max(0,t.p-u.p),c:Math.max(0,t.c-u.c),f:Math.max(0,t.f-u.f)}}
function mealGoal(meal){let rem=remaining(),idx=mealOrder.indexOf(meal),left=mealOrder.slice(Math.max(0,idx)),den=left.reduce((a,m)=>a+mealSplit[m],0)||1,w=mealSplit[meal]/den;return{kcal:rem.kcal*w,p:rem.p*w,c:rem.c*w,f:rem.f*w}}

function bmr(){let p=state.profile;return 447.593+9.247*p.weight+3.098*p.height-4.33*p.age}function target(type){let p=state.profile,k=bmr()*p.activity*(1-p.deficit/100),m=state.macros[type];return{kcal:k,p:k*m[0]/100/4,c:k*m[1]/100/4,f:k*m[2]/100/9}}
function dayName(d=new Date()){return ['Dimanche','Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi'][d.getDay()]}function key(){return new Date().toISOString().slice(0,10)}function typeToday(){return state.weekOverrides[key()]||state.week[dayName()]||'A'}
function totals(){return (state.consumed[key()]||[]).reduce((a,x)=>({kcal:a.kcal+(+x.kcal||0),p:a.p+(+x.p||0),c:a.c+(+x.c||0),f:a.f+(+x.f||0)}),{kcal:0,p:0,c:0,f:0})}
function fmt(n,d=0){return Number(n).toLocaleString('fr-CH',{maximumFractionDigits:d,minimumFractionDigits:d})}
function renderToday(){let t=target(typeToday()),u=totals();dateLabel.textContent=new Date().toLocaleDateString('fr-CH',{weekday:'long',day:'numeric',month:'long'});dayType.textContent=`Journée ${typeToday()}`;metrics.innerHTML=[['Calories','kcal','kcal'],['Protéines','g','p'],['Glucides','g','c'],['Lipides','g','f']].map(([n,unit,k])=>{let pct=Math.min(100,u[k]/t[k]*100||0);return `<div class="metric"><small>${n}</small><strong>${fmt(u[k],k==='kcal'?0:1)} <small>/ ${fmt(t[k],k==='kcal'?0:1)} ${unit}</small></strong><div class="bar"><i style="width:${pct}%"></i></div><small>${fmt(Math.max(0,t[k]-u[k]),k==='kcal'?0:1)} ${unit} restant</small></div>`}).join('');let rem={kcal:Math.max(0,t.kcal-u.kcal),p:Math.max(0,t.p-u.p),c:Math.max(0,t.c-u.c),f:Math.max(0,t.f-u.f)};meals.innerHTML=Object.entries(mealSplit).map(([m,s])=>`<div class="meal"><div class="row"><div><b>${m}</b><div class="facts">Cible actuelle ≈ ${fmt(rem.kcal*s)} kcal · ${fmt(rem.p*s,1)} g P · ${fmt(rem.c*s,1)} g G · ${fmt(rem.f*s,1)} g L</div></div><button onclick="suggestMeal('${m}')">Recette</button></div></div>`).join('');let arr=state.consumed[key()]||[];extras.innerHTML=arr.length?arr.map(x=>`<div class="history"><b>${x.name}</b><div class="facts">${fmt(x.kcal)} kcal · P ${fmt(x.p,1)} g · G ${fmt(x.c,1)} g · L ${fmt(x.f,1)} g</div></div>`).join(''):'<p class="muted">Rien ajouté aujourd’hui.</p>'}
function renderWeek(){weekGrid.innerHTML=Object.entries(state.week).map(([d,t])=>`<button class="weekDay" onclick="cycleDay('${d}')"><span><b>${d}</b><small style="display:block">${d===dayName()?'Aujourd’hui':''}</small></span><span class="typeBadge">${t}</span></button>`).join('')}
function cycleDay(d){state.week[d]=state.week[d]==='A'?'B':state.week[d]==='B'?'C':'A';save();renderWeek();if(d===dayName())renderToday()}
function renderRecipes(filter='all'){let all=[...recipes,...state.customRecipes];recipeList.innerHTML=all.filter(r=>filter==='all'||r.cat===filter).map((r,i)=>`<div class="recipe"><div class="row"><div><b>${r.name}</b><small>${r.cat}</small></div><span>♡</span></div><div>${r.ingredients}</div><div class="facts">${fmt(r.kcal)} kcal · P ${fmt(r.p,1)} g · G ${fmt(r.c,1)} g · L ${fmt(r.f,1)} g</div>${r.customItems?.length?'<small class="muted">Recette personnelle ajustable automatiquement</small>':''}</div>`).join('')}
function renderProgress(){let a=state.measures;latestMeasure.innerHTML=a.length?`Dernier relevé : <b>${a.at(-1).weight} kg</b> · ${a.at(-1).date}`:'Aucune mesure enregistrée.';measureHistory.innerHTML=a.length?[...a].reverse().map(x=>`<div class="history"><b>${x.date} — ${x.weight} kg</b><div class="facts">Taille ${x.waist||'—'} cm · Ventre ${x.belly||'—'} · Hanches ${x.hips||'—'} · Poitrine ${x.chest||'—'} · Cuisse ${x.thigh||'—'} · Bras ${x.arm||'—'}</div></div>`).join(''):'<p class="muted">Ton historique apparaîtra ici.</p>'}
function renderSettings(){weight.value=state.profile.weight;height.value=state.profile.height;age.value=state.profile.age;deficit.value=state.profile.deficit;activity.innerHTML=activities.map(([n,v])=>`<option value="${v}" ${+state.profile.activity===v?'selected':''}>${n} ×${v}</option>`).join('');macroSettings.innerHTML=Object.entries(state.macros).map(([k,v])=>`<div class="macroRow"><b>${k}</b>${['P','G','L'].map((n,i)=>`<label>${n}%<input data-type="${k}" data-i="${i}" type="number" value="${v[i]}"></label>`).join('')}</div>`).join('');preview()}
function preview(){let p={...state.profile,weight:+weight.value||0,height:+height.value||0,age:+age.value||0,activity:+activity.value||1.2,deficit:+deficit.value||0};let base=447.593+9.247*p.weight+3.098*p.height-4.33*p.age,k=base*p.activity*(1-p.deficit/100);calcPreview.innerHTML=`Métabolisme de base : <b>${fmt(base)} kcal</b><br>Objectif avec activité et déficit : <b>${fmt(k)} kcal/j</b>`}
function modal(html){modalBody.innerHTML=html;document.getElementById('modal').showModal()}
changeToday.onclick=()=>modal(`<h3>Type de journée</h3><p>Ce changement concerne aujourd’hui uniquement.</p><div class="modalActions">${['A','B','C'].map(x=>`<button type="button" onclick="setToday('${x}')">${x}</button>`).join('')}<button>Annuler</button></div>`);window.setToday=x=>{state.weekOverrides[key()]=x;save();document.getElementById('modal').close();renderToday()}
addConsumed.onclick=()=>modal(`<h3>Ajouter une consommation</h3><label>Nom<input id="mName" placeholder="Ex. verre de vin rouge"></label><label>Calories<input id="mKcal" type="number"></label><div class="macroRow"><b></b><label>P g<input id="mP" type="number" step="0.1"></label><label>G g<input id="mC" type="number" step="0.1"></label><label>L g<input id="mF" type="number" step="0.1"></label></div><p class="kcalNote">Pour l’alcool, les calories peuvent dépasser celles expliquées par P/G/L : elles seront comptées dans le total calorique.</p><div class="modalActions"><button>Annuler</button><button type="button" class="primary" onclick="addItem()">Ajouter</button></div>`);window.addItem=()=>{state.consumed[key()]??=[];state.consumed[key()].push({name:mName.value||'Consommation',kcal:+mKcal.value||0,p:+mP.value||0,c:+mC.value||0,f:+mF.value||0});save();document.getElementById('modal').close();renderToday()}
rebalance.onclick=()=>{let rem=remaining();let cards=mealOrder.map(m=>{let g=mealGoal(m),pool=recipes.filter(r=>r.cat===m).map(r=>({r,fit:fitRecipe(r,g)})).filter(x=>x.fit).sort((a,b)=>a.fit.score-b.fit.score);if(!pool.length)return'';let x=pool[0];return `<div class="rebCard"><b>${m}</b><span>${x.r.name}</span><small>${fmt(x.fit.kcal)} kcal · P ${fmt(x.fit.p,1)} · G ${fmt(x.fit.c,1)} · L ${fmt(x.fit.f,1)}</small></div>`}).join('');modal(`<h3>Rééquilibrage intelligent</h3><p>Il te reste <b>${fmt(rem.kcal)} kcal</b> · P ${fmt(rem.p,1)} g · G ${fmt(rem.c,1)} g · L ${fmt(rem.f,1)} g.</p><p class="muted">Voici des recettes dont les grammages peuvent être ajustés. Ouvre le repas depuis l’écran Aujourd’hui pour voir les quantités exactes.</p>${cards}<div class="modalActions"><button>OK</button></div>`)}

window.suggestMeal=m=>{let pool=[...recipes,...state.customRecipes].filter(r=>r.cat===m),goal=mealGoal(m);let ranked=pool.map(r=>({r,fit:fitRecipe(r,goal)})).sort((a,b)=>(a.fit?.score??99)-(b.fit?.score??99));let {r,fit}=ranked[0];if(!fit){modal(`<h3>${r.name}</h3><p>${r.ingredients}</p><p><b>${r.kcal} kcal</b> · P ${r.p} g · G ${r.c} g · L ${r.f} g</p><p class="muted">Cette recette personnelle n’a pas encore d’ingrédients nutritionnels structurés, donc ses grammages ne peuvent pas être optimisés automatiquement.</p><div class="modalActions"><button>Fermer</button></div>`);return}let detail=fit.items.map(i=>`<div class="adjustLine"><span>${i.n}</span><b>${fmt(i.g)} g</b></div>`).join('');modal(`<h3>${r.name}</h3><p class="muted">Portion proposée selon ce qu’il te reste aujourd’hui pour ${m.toLowerCase()}.</p><div class="adjustBox">${detail}</div><p><b>${fmt(fit.kcal)} kcal</b> · P ${fmt(fit.p,1)} g · G ${fmt(fit.c,1)} g · L ${fmt(fit.f,1)} g</p><p class="facts">Cible repas ≈ ${fmt(goal.kcal)} kcal · P ${fmt(goal.p,1)} · G ${fmt(goal.c,1)} · L ${fmt(goal.f,1)}</p><div class="modalActions"><button>Fermer</button><button type="button" class="primary compact" onclick='eatAdjusted(${JSON.stringify(JSON.stringify({name:r.name,kcal:fit.kcal,p:fit.p,c:fit.c,f:fit.f})).slice(1,-1)})'>J’ai mangé ça</button></div>`)}
window.eatAdjusted=json=>{let x=typeof json==='string'?JSON.parse(json):json;state.consumed[key()]??=[];state.consumed[key()].push(x);save();document.getElementById('modal').close();renderToday()}

newMeasure.onclick=()=>modal(`<h3>Nouvelle mesure</h3><label>Poids (kg)<input id="mw" type="number" step="0.1" value="${state.profile.weight}"></label>${[['waist','Tour de taille'],['belly','Ventre'],['hips','Hanches'],['chest','Poitrine'],['thigh','Cuisse'],['arm','Bras']].map(([i,n])=>`<label>${n} (cm)<input id="${i}" type="number" step="0.1"></label>`).join('')}<div class="modalActions"><button>Annuler</button><button type="button" class="primary" onclick="addMeasure()">Enregistrer</button></div>`);window.addMeasure=()=>{state.measures.push({date:new Date().toLocaleDateString('fr-CH'),weight:+mw.value,waist:waist.value,belly:belly.value,hips:hips.value,chest:chest.value,thigh:thigh.value,arm:arm.value});save();document.getElementById('modal').close();renderProgress()}
let recipeDraft=[];
function ingredientRows(){let box=document.getElementById('ingredientRows');if(!box)return;box.innerHTML=recipeDraft.map((x,i)=>`<div class="ingredientEditor"><div class="row"><b>Ingrédient ${i+1}</b><button type="button" onclick="removeIngredient(${i})">×</button></div><label>Nom<input data-r="${i}" data-k="n" value="${x.n||''}" placeholder="Ex. poulet"></label><div class="macroRow"><label>Quantité g<input data-r="${i}" data-k="g" type="number" step="1" value="${x.g||100}"></label><label>Min g<input data-r="${i}" data-k="min" type="number" step="1" value="${x.min||Math.max(0,(x.g||100)*.6)}"></label><label>Max g<input data-r="${i}" data-k="max" type="number" step="1" value="${x.max||(x.g||100)*1.5}"></label></div><small>Valeurs nutritionnelles pour 100 g</small><div class="macroRow"><label>kcal<input data-r="${i}" data-k="k" type="number" step="0.1" value="${x.k||0}"></label><label>P g<input data-r="${i}" data-k="p" type="number" step="0.1" value="${x.p||0}"></label><label>G g<input data-r="${i}" data-k="c" type="number" step="0.1" value="${x.c||0}"></label><label>L g<input data-r="${i}" data-k="f" type="number" step="0.1" value="${x.f||0}"></label></div></div>`).join('');box.querySelectorAll('input').forEach(el=>el.oninput=()=>{let i=+el.dataset.r,k=el.dataset.k;recipeDraft[i][k]=k==='n'?el.value:+el.value;updateRecipePreview()});updateRecipePreview()}
function updateRecipePreview(){let out=document.getElementById('recipePreview');if(!out)return;let grams=recipeDraft.map(x=>+x.g||0),t=sumIngredients(recipeDraft,grams);out.innerHTML=`Total recette : <b>${fmt(t.kcal)} kcal</b> · P ${fmt(t.p,1)} g · G ${fmt(t.c,1)} g · L ${fmt(t.f,1)} g`}
window.addIngredient=()=>{recipeDraft.push({n:'',g:100,min:50,max:150,k:0,p:0,c:0,f:0});ingredientRows()};window.removeIngredient=i=>{recipeDraft.splice(i,1);ingredientRows()};
newRecipe.onclick=()=>{recipeDraft=[{n:'',g:100,min:50,max:150,k:0,p:0,c:0,f:0}];modal(`<h3>Nouvelle recette</h3><label>Nom<input id="rn"></label><label>Repas<select id="rc"><option>Petit-déjeuner</option><option>Déjeuner</option><option>Collation</option><option>Dîner</option></select></label><p class="muted">Pour chaque ingrédient, indique les valeurs de l’étiquette pour 100 g. Min/Max définissent jusqu’où l’appli peut ajuster sa quantité.</p><div id="ingredientRows"></div><button type="button" onclick="addIngredient()">+ Ajouter un ingrédient</button><div id="recipePreview" class="kcalNote"></div><div class="modalActions"><button>Annuler</button><button type="button" class="primary" onclick="addRecipe()">Enregistrer</button></div>`);ingredientRows()};
window.addRecipe=()=>{recipeDraft.forEach(x=>{x.g=+x.g||0;x.min=Math.max(0,+x.min||0);x.max=Math.max(x.min,+x.max||x.g);for(let k of ['k','p','c','f'])x[k]=+x[k]||0});let valid=recipeDraft.filter(x=>x.n&&x.g>0);if(!rn.value.trim()||!valid.length){alert('Ajoute un nom et au moins un ingrédient.');return}let t=sumIngredients(valid,valid.map(x=>x.g)),desc=valid.map(x=>`${fmt(x.g)} g ${x.n}`).join(' · ');state.customRecipes.push({name:rn.value.trim(),cat:rc.value,ingredients:desc,kcal:t.kcal,p:t.p,c:t.c,f:t.f,customItems:valid});save();document.getElementById('modal').close();renderRecipes()};
saveSettings.onclick=()=>{state.profile={weight:+weight.value,height:+height.value,age:+age.value,activity:+activity.value,deficit:+deficit.value};document.querySelectorAll('[data-type]').forEach(i=>state.macros[i.dataset.type][+i.dataset.i]=+i.value);save();renderToday();preview();alert('Paramètres enregistrés')};[weight,height,age,activity,deficit].forEach(x=>x.oninput=preview);document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(b.dataset.view).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on')});document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chips button').forEach(x=>x.classList.remove('on'));b.classList.add('on');renderRecipes(b.dataset.filter)});
let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;installBtn.hidden=false});installBtn.onclick=async()=>{if(deferred){deferred.prompt();deferred=null;installBtn.hidden=true}};if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderToday();renderWeek();renderRecipes();renderProgress();renderSettings();
